get_filename_component(NORDIC_CMAKE_DIR ${CMAKE_CURRENT_LIST_FILE} DIRECTORY)
list(APPEND CMAKE_MODULE_PATH ${NORDIC_CMAKE_DIR})

include(base)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
find_program(CMAKE_C_COMPILER NAMES ${NORDIC_TARGET_TRIPLET}-gcc PATHS ${TOOLCHAIN_BIN_PATH} )
find_program(CMAKE_CXX_COMPILER NAMES ${NORDIC_TARGET_TRIPLET}-c++ PATHS ${TOOLCHAIN_BIN_PATH} )
find_program(CMAKE_ASM_COMPILER NAMES ${NORDIC_TARGET_TRIPLET} PATHS ${TOOLCHAIN_BIN_PATH} )
find_program(CMAKE_SIZE_UTIL NAMES ${NORDIC_TARGET_TRIPLET}-size PATHS ${TOOLCHAIN_BIN_PATH} )
find_program(CMAKE_OBJCOPY NAMES ${NORDIC_TARGET_TRIPLET}-objcopy PATHS ${TOOLCHAIN_BIN_PATH} )